# Generated by Django 4.1.2 on 2022-10-24 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nome_cidade', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('carga_horaria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('curso', models.CharField(choices=[('TÉCNICO EM INFORMÁTICA', 'TÉCNICO EM INFORMÁTICA'), ('TÉCNICO EM ALIMENTOS', 'TÉCNICO EM ALIMENTOS'), ('TÉCNICO EM APICULTURA', 'TÉCNICO EM APICULTURA'), ('QUÍMICA', 'QUÍMICA'), ('ADS', 'ADS')], max_length=150)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campus')),
                ('disciplinas', models.ManyToManyField(to='main.disciplina')),
            ],
        ),
    ]
