# Generated by Django 4.1.2 on 2022-10-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_disciplina_professores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='oferta',
            name='oferta',
            field=models.ManyToManyField(to='main.aluno'),
        ),
    ]
