# Generated by Django 4.1.2 on 2022-10-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_aluno_disciplinas_oferta_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='campus',
        ),
    ]
