# Generated by Django 4.1.2 on 2022-10-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_aluno_campus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='oferta',
            new_name='alunos',
        ),
    ]
